spring:
  application:
    name: picpay

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/picpaydb
    username: admin
    password: adminpwd
    driver-class-name: com.mysql.cj.jdbc.Driver

client:
  authorization-service:
    url: http://localhost:8090
  notification-service:
    url: http://localhost:9090
